### ISSUE TITLE
Color scheme

### ISSUE THREAD

**Issue by Capplequoppe** [MoralisWeb3/issue-tracker#1]
Streamline the color scheme to reflect the Moralis brand
![image](https://user-images.githubusercontent.com/7919855/110958877-6f6bfa80-834d-11eb-8237-0f2746ded3c1.png)

**Comment by gerardo15** [comment]
Fixed, all colors are now uniform.

**Comment by Capplequoppe** [comment]
![image](https://user-images.githubusercontent.com/7919855/111463675-1ff84680-8720-11eb-9352-9b61b5700529.png)
The select border and the button still have different colors, but maybe it does not matter @gerardo15
