### ISSUE TITLE
Server Instance

### ISSUE THREAD

**Issue by voljumet** [MoralisWeb3/issue-tracker#10]
In Server Instance -> Ganache Proxy Server
I think it's a bit unclear. I was looking for information on how to apply the copied code.
"2. Copy the following content in the same folder of frp as "frpc.ini", this code assumes your ganache instance is hosted at port 7545"
to make it simpler to understand, it should be rewritten to something like:
"2. Replace the content in the file "frpc.ini" inside the frp folder with the following code, the code assumes your ganache instance is hosted at port 7545"

**Comment by gerardo15** [comment]
Fixed! Thanks for your reporting this!
