### ISSUE TITLE
Duplicated tokens in nft/{contract_address}/owners

### ISSUE THREAD

**Issue by Pitozzi** [MoralisWeb3/issue-tracker#116]
Hello!

I'm trying to get the owners of an NFT collection with:
https://deep-index.moralis.io/api/v2/nft/0xe9eee7294dc7c3bb64fd57a514e755022a333295/owners

But some tokens have several entries, like if they were duplicated.
The collection has 10k NFTs but I can gather 10'037 with the request.
Moreover, the tokens that are duplicated show different owners, so that's a mess.

As an example, I get the NFT #9486 twice, with 0x712bec7191c264109d385de8d36b2e746b31696a, its current owner but also with 0xee55918d2fd4a1fed4a6c6f8878dd3f8ff08abd5 its previous owner.
https://opensea.io/assets/matic/0xe9eee7294dc7c3bb64fd57a514e755022a333295/9486

They always arrive just after one another in the Moralis response.

**Comment by ivan-liljeqvist** [comment]
Hi please post in https://forum.moralis.io thanks!
