### ISSUE TITLE
"Join the Beta" --> "Accept Invite"  is not working!

### ISSUE THREAD

**Issue by ieszeki** [MoralisWeb3/issue-tracker#12]
Hello, 

When I clicked on "Join the Beta" in my "Welcome to Moralis" email sent to me and clicked on "Accept Invite" then I got the following error on Discord: "Messages Failed To Load". Please see attached screenshots. 
<img width="608" alt="first" src="https://user-images.githubusercontent.com/20509497/111230566-0da5cd80-85a5-11eb-951d-159f53ccc077.png">
<img width="1015" alt="second" src="https://user-images.githubusercontent.com/20509497/111230579-13031800-85a5-11eb-8843-493a7cadf648.png">
<img width="1363" alt="third" src="https://user-images.githubusercontent.com/20509497/111230594-19918f80-85a5-11eb-9c36-3a89bdf74f35.png">

Thank you,

greentree

**Comment by filipmartinsson** [comment]
Replaced the link with a new one that should go to #general
