### ISSUE TITLE
Unresponsive login button when using a password manager

### ISSUE THREAD

**Issue by Capplequoppe** [MoralisWeb3/issue-tracker#13]
When using a password manager that is auto filling the credentials, the logic for enabling the button is faulty, making the button still disabled and therefor unresponsive.
If the user changes any of the fields, the button becomes enabled again.
![image](https://user-images.githubusercontent.com/7919855/111322868-aa31a380-8669-11eb-8df2-25966cebc8a6.png)

**Comment by gerardo15** [comment]
Fixed.
