### ISSUE TITLE
Feedback survey has some smaller bugs

### ISSUE THREAD

**Issue by ctrl030** [MoralisWeb3/issue-tracker#14]
- when asked if we will use moralis in the future, when you answer "Yes", the next question assumes you answered "No"

- the last page of the survey has template text "Custom Thank you Screen A" or "When your respondent clicks the button below..."

**Comment by TotalingArc** [comment]
lol thought it was a trick question.

**Comment by filipmartinsson** [comment]
Fixed, thank you!
