### ISSUE TITLE
Read More button links to current page

### ISSUE THREAD

**Issue by denishacquin** [MoralisWeb3/issue-tracker#16]
[![Screenshot_2021-03-18_12-56-37.png](https://s3-eu-west-1.amazonaws.com/codename.screenshots.test/18864d93115e4b97a4c7971e781966c6-1000x1000-1616068597271.png)](https://s3-eu-west-1.amazonaws.com/codename.screenshots.test/e6dee34bd9be469790435799fcbb61ad-10000x10000-1616068597267.png)

Steps to reproduce:
Go to moralis.io and scroll down

Actual result:
The button reloads the same page

Expected result:
Should link to a section or another page

---

**Source URL:** [https://moralis.io/](https://moralis.io/)

<table><tr><td><strong>Browser</strong></td><td>Chrome 89.0.4389.82</td></tr><tr><td><strong>Screen Size</strong></td><td>1920 x 1080</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.6</td></tr><tr><td><strong>Viewport Size</strong></td><td>1920 x 978</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

Reported with [Marker.io](https://marker.io/)

**Comment by filipmartinsson** [comment]
Solved
