### ISSUE TITLE
Fix for Demo app Casino CONTRACT_ADDRESS

### ISSUE THREAD

**Issue by carry2web** [MoralisWeb3/issue-tracker#17]
Line 47 in main.js is:
    window.contract = new web3.eth.Contract(contractAbi, "CONTRACT_ADDRESS");

should be:

    window.contract = new web3.eth.Contract(contractAbi, CONTRACT_ADDRESS);

as  CONTRACT_ADDRESS is defined as a const in top of file and should be passed as such.

**Comment by filipmartinsson** [comment]
Fixed. Thanks!
