### ISSUE TITLE
Documentation assumes too much prior knowledge

### ISSUE THREAD

**Issue by SimonJamesOdell** [MoralisWeb3/issue-tracker#19]
Hi guys, as requested over on discord here is a summary of the feedback I offered regarding the documenation.

- The docs assume various prerequisite knowledge, such as knowing what "Ganache" is and whether it's going to be used or not.
- The learning curve is somewhat steep without an overview of the programming and architechtural landscape that Moralis occupies.

I suggest adding a section entitled something like "Prerequisite Knowledge" which gives a breif overview of how you expect Moralis to be used and what technologies are needed / recommended to be used with it, along with some links to further reading. The information can probably safely assume the reader has a firm understanding on a modern javascript stack, but should not assume they are familiar with the cryptosphere technologies.

**Comment by jermay** [comment]
This is a great suggestion. I've added an intro section and will go through the Web3 stuff and add more introductory comments... any other specific suggestions you have would be very helpful.

https://docs.moralis.io/#welcome-to-moralis-beta

**Comment by gerardo15** [comment]
Great! @jermay i have also added a Pre-Requisites tab on the docs

https://docs.moralis.io/pre-requisites

@SimonJamesOdell let us know if we could add something more or we are missing something!

Thanks for taking your time for this!

**Comment by SimonJamesOdell** [comment]
I'm guessing English is not your first language, if you want I can help by doing a pull request with some improvements to grammar and some further additions like links on the pre-requisites page.

**Comment by gerardo15** [comment]
@SimonJamesOdell Amazing!

I added the file to this repo so you can pull-request:

https://github.com/MoralisWeb3/issue-tracker/blob/main/files/pre-requisites.md

**Comment by jermay** [comment]
I've made some edits for grammar, added links and a "Software" section. 

How does this look now?

**Comment by jermay** [comment]
If there are additional suggestions please create another issue. Will close this one.
