### ISSUE TITLE
Data access / permissions

### ISSUE THREAD

**Issue by matjaz** [MoralisWeb3/issue-tracker#26]
By default all permissions are public. What are best practice to restrict read/write access? before events, validation, ACL... any good (Parse) tutorials?

**Comment by rphansen91** [comment]
@matjaz Great suggestion ACL and CLP are both supported. 

Will add documentation and create tutorials as suggested.

Right now the ACL can be edited in the dashboard and Private values can be added as follows

```
var privateData = Moralis.Object.extend("PrivateUserData");
privateData.setACL(new Moralis.ACL(Moralis.User.current()));
privateData.set("phoneNumber", "555-5309");
privateData.save()
```

**Comment by matjaz** [comment]
Getting started: http://docs.parseplatform.org/js/guide/#security
