### ISSUE TITLE
BUG: $ in Cloud Function Queries produces error on save

### ISSUE THREAD

**Issue by jermay** [MoralisWeb3/issue-tracker#30]
Steps to reproduce:
1. Create a Cloud Function with a query that contains a `$` as required by the Mongo syntax
2. Paste the code into the Cloud Function section on a Moralis Server instance
3.  Press the Save button... an error occurs

WORKAROUND: escape `$` with `\$`

This is a known issue. Documenting here so it doesn't get lost.

**Comment by gerardo15** [comment]
Fixed.
