### ISSUE TITLE
Calling burn on a token contract should remove the token from EthTokenBalance

### ISSUE THREAD

**Issue by matiyin** [MoralisWeb3/issue-tracker#32]
When you mint a new token it appears in EthTokenBalance automatically.
When you burn it, it should also be removed from EthTokenBalance automatically.

**Comment by gerardo15** [comment]
Are you experiencing this in ERC20 and ERC721?

**Comment by matiyin** [comment]
ERC721 for me, didn't test ERC20 yet. 
to_address on EthTokenTransfers shows a correct 0x00000000000000000000000000000000 address.

**Comment by gerardo15** [comment]
Fixed on 0.0.162
