### ISSUE TITLE
Dashboard UI clipping

### ISSUE THREAD

**Issue by jermay** [MoralisWeb3/issue-tracker#33]
At smaller window sizes there are some UI clipping issues with the left hand menu. Like if I want to snap the dashboard to the left or right side of the desktop:
![image](https://user-images.githubusercontent.com/12789154/113636112-cc925d80-9626-11eb-870d-eced01835e28.png)

**Comment by Capplequoppe** [comment]
Fixed in dashboard version 0.0.10
