### ISSUE TITLE
404 Code when trying to delete a scheduled job

### ISSUE THREAD

**Issue by Capplequoppe** [MoralisWeb3/issue-tracker#4]
When trying to delete a scheduled job in the dashboard, noting happens and I get a 404 response in the console
![image](https://user-images.githubusercontent.com/7919855/111028611-fd9cbb00-83f7-11eb-8e8f-4c15ae653471.png)

**Comment by gerardo15** [comment]
Fixed, This will be included in the next version (0.0.100), please reopen this issue if the problem persist.
