### ISSUE TITLE
Server gets stuck loading if updated with corrupt cloud code

### ISSUE THREAD

**Issue by Capplequoppe** [MoralisWeb3/issue-tracker#52]
If a server is updated with invalid Cloud code, the server is frozen.
When manually updating the server, perhaps a 20 second  extra waiting time is ok, since updates are not done so often.
![image](https://user-images.githubusercontent.com/7919855/115103699-3e867300-9f54-11eb-87f7-0c229b85114f.png)

**Comment by gerardo15** [comment]
fixed in the latest version, prevent upload/restart if corrupt cloud code
