### ISSUE TITLE
user.set() method not creating new column (second tutorial)

### ISSUE THREAD

**Issue by hlairboltons** [MoralisWeb3/issue-tracker#56]
The following code allows me to sign a metamask signature, however when using set.user() method as Ivan did in the second tutorial, it does not create a new column of data for user. I refresh the moralis dashboard many times but no updating of colums for the user tab

e.g.

async function login() {
  			console.log("login clwicked");
  			var user = await Moralis.Web3.authenticate();
  			if(user){
  				console.log(user);
  				user.set("nickname", "elon");
  				user.set("birthday", 11081992);
  			}
  		}

There are no errors returned.

![Capture](https://user-images.githubusercontent.com/48202694/115477950-69d8cd00-a288-11eb-8ae5-8ef09876c741.PNG)

**Comment by Capplequoppe** [comment]
In order to persist the data, you need to call `await user.save()`
