### ISSUE TITLE
Add "Edit Plugin" Capability

### ISSUE THREAD

**Issue by aglawson** [MoralisWeb3/issue-tracker#57]
Rather than requiring the user to create an entirely new plugin when they want to change an aspect of a plugin, add an "edit plugin" functionality. For example, whenever I redeploy a smart contract, I need to put the new contract address into the plugin that syncs and watches contract events. When I do this, I have to create a new plugin, re-enter the same details and add the new contract address. It would make for better ease of use if I could just click "edit plugin" and change the contract address, since the other details will remain the same.

**Comment by gerardo15** [comment]
Fixed on Moralis 1.0
