### ISSUE TITLE
Devcahin Proxy Server copy/paste button error

### ISSUE THREAD

**Issue by jermay** [MoralisWeb3/issue-tracker#59]
View Server > Devchain Proxy server tab
When you click on the "copy" button for the `frpc` command it should not include the OS label that's in brackets:

![image](https://user-images.githubusercontent.com/12789154/115967826-9c353500-a4e9-11eb-83b7-41e66253aecb.png)

Results:
` ./frpc -c frpc.ini (Linux)`
` frpc.exe -c frpc.ini (Windows)`

Expected:
` ./frpc -c frpc.ini`
` frpc.exe -c frpc.ini`

**Comment by Capplequoppe** [comment]
Will be fixed in 0.0.188
