### ISSUE TITLE
Query select does nothing

### ISSUE THREAD

**Issue by jermay** [MoralisWeb3/issue-tracker#63]
If you type the following into the dashboard console with a valid user address that exists in the Moralis database it returns all columns instead of the specific ones defined in the `select`. Same behavior for queries called from the browser or in Cloud Functions.

```javascript
const userAddress = "0x...";
const tokenQuery = new Parse.Query("EthTokenBalance");
tokenQuery.equalTo("address", userAddress)
  .select("name", "symbol", "balance", "decimals");
const tokenResult = await tokenQuery.find();
console.log(tokenResult);
```

**Comment by gerardo15** [comment]
Tested on latest version and working, reopen if we are able to replicate again
