### ISSUE TITLE
Invalid session token moralis.js

### ISSUE THREAD

**Issue by nclbill** [MoralisWeb3/issue-tracker#65]
hi 
i creat a server on moralis and a buton  to login with Metamask  
im using:
moralis mainet , localhost  to execute this function
		async function login(){
			console.log("login clicked");
			var user = await Moralis.Web3.authenticate();
			if(user){
				console.log(user);
				user.set("nickname","VITALIK");
				user.set("fav_color","black");
				user.save();
			}
		}
first time it works and i got  i new user in the moralis servers and i add data to new row. after when login, in console i have
"Uncaught (in promise) Error: Invalid session token"
can someone help tks

**Comment by ivan-liljeqvist** [comment]
You are probably trying to sign up a user that is already logged in?
If the user is logged in - log out first before authenticating
