### ISSUE TITLE
Relational query not returning data

### ISSUE THREAD

**Issue by jermay** [MoralisWeb3/issue-tracker#67]
I think the relation query docs are incorrect
https://docs.moralis.io/objects#relational-data

There is no "success" callback function defined on `ParseQuery.find()` see the API docs here:
http://parseplatform.org/Parse-SDK-JS/api/3.2.0/Parse.Query.html#find

When I try using promises in the Moralis Dashboard JS Console it returns no data. In the Browser the data and relations are defined and can be navigated through.

![image](https://user-images.githubusercontent.com/12789154/117857974-3ca58c00-b242-11eb-97c1-5f4a181b4126.png)

![image](https://user-images.githubusercontent.com/12789154/117857545-bc7f2680-b241-11eb-8ee8-0a1874147733.png)

```javascript
let character = await new Parse.Query("Character")
  .equalTo("name", "Friar")
  .first();
console.log(character);

const inventoryItems = await character.relation("inventory").query().find();
console.log(inventoryItems);
```

![image](https://user-images.githubusercontent.com/12789154/117857524-b721dc00-b241-11eb-927a-2b6be30fa6a6.png)

**Comment by nconfrey** [comment]
Any update on this? Also finding that queries on relations are not returning anything:
```
let relation = page.relation("posts")
      relation.query().find({
        success: function (list) {
          console.log("connection page successfully found posts:", posts)
          setPosts(posts)
          setIsLoading(false)
        }, error: function(error) {
          console.log("ERROR: ", error)
        }
      });
```
Never hits the success callback.

**Comment by ivan-liljeqvist** [comment]
This is solved I think long time ago

for all questions and discussions please use forum https://forum.moralis.io

**Comment by nconfrey** [comment]
Hello past Nick, the Moralis documentation is wrong here, that's why you got stuck. Try calling `find()` and then waiting for the promise to resolve:
```
const connectionsRelation = currentAccount.relation("Connections")
    connectionsRelation.query().find().then(function (results) {
      setConnections(results)
    })
      .catch(function (error) {
        console.log(error)
      })
```
