### ISSUE TITLE
At EVM Config it says: You can enable multiple Layer 2s here | No L2's are suported

### ISSUE THREAD

**Issue by amadeobrands** [MoralisWeb3/issue-tracker#68]
I think it is better to call these side chains.
![image](https://user-images.githubusercontent.com/6133031/118412869-a5ef2a00-b69c-11eb-9602-8823a8eab74a.png)

Looking forward to integrations with zkSync or StarkWare etc?

**Comment by jermay** [comment]
This UI is temporary and will be changed. You're correct, it's more accurate to say EVM compatible side chains.

**Comment by jermay** [comment]
This text was removed in the new UI. Now says "Select chains".
