### ISSUE TITLE
ETH count mismatch in metamask (Ganache devchain), Moralis Ganache setup issue

### ISSUE THREAD

**Issue by biplabro** [MoralisWeb3/issue-tracker#73]
Hello,

I have been following the “3-minutes dapp” tutorial & stuck at the Ganache sections. https://docs.moralis.io/guides/deploy-and-track-erc20-events
2 issues

a) the amount of of ETH in Ganache program does not match with the ETH available in the Metamask account (Local ganache dev chain)

b) Cannot connect Ganache to Moralis server. The Local Dev chain “Ganache” option is missing.
https://youtu.be/aRRS394is1U?t=55

Created a brief video explaining the issue. Any help in this regard would be very helpful.
https://drive.google.com/file/d/1w_PycDgME-beV_erOPa645l1OUGgR19n/view?usp=sharing

Thanks & Cheers,
Roy

**Comment by biplabro** [comment]
Issue 1: Resolved.
Server side issue pending

https://forum.moralis.io/t/eth-count-mismatch-in-metamask-ganache-devchain-moralis-ganache-setup-issue/467

**Comment by gerardo15** [comment]
Hello,

We have deleted the stuck server, please create a new.

**Comment by biplabro** [comment]
Thanks @gerardo15

**Comment by biplabro** [comment]
Please share a little more detail about why it happened & how to avoid such scenarios in the future?
