### ISSUE TITLE
Moralis Dashbord FrontEnd Bug

### ISSUE THREAD

**Issue by DmKodoff** [MoralisWeb3/issue-tracker#82]
![image](https://user-images.githubusercontent.com/72114399/122642235-ec242700-d13b-11eb-9587-3434473fb996.png)

The panels cover the button for applying changes. 
This bug In the Modal Popup for  "Select Pointer", if changing row in DB

Chrome /Windows

**Comment by ivan-liljeqvist** [comment]
Please post in https://forum.moralis.io - we have staff actively checking there
