### ISSUE TITLE
Moralis.Web3.getNFTs(); not working for Eth Chain

### ISSUE THREAD

**Issue by Peacanduck** [MoralisWeb3/issue-tracker#83]
const options = { chain: 'Binance Smart Chain', address: '0x5d3878F40739a82fa327B68Cfb02a56a80e764a8' };
let  ownedItems = await Moralis.Web3.getNFTs(options);

only returns values when chain is = to "Binance Smart Chain" or "matic". returns error 400 on "Eth"

**Comment by ivan-liljeqvist** [comment]
Please post in https://forum.moralis.io - we have staff actively checking there
