### ISSUE TITLE
accountBalanceGet on AccountAPI returns error 500

### ISSUE THREAD

**Issue by microHoffman** [MoralisWeb3/issue-tracker#85]
Hello, I downloaded the Moralis API client (Typescript fetch version) and I am trying to get account balances:

```
const apiConfig = new Configuration({ apiKey: "xxx", });
const accountService = new AccountApi(apiConfig);
const balance = await accountService.accountBalanceGet(TOKAddress, undefined, "kovan");
```
GET request:
```
https://deep-index.moralis.io/api/account/balance?chain_name=kovan&address=0xEA8A39bfAB9E059Ec5f4F878862D0Ba52841725C
```
However this call returns me 500 error. I think it should not be a problem in the api config, as for example TokenApi method tokenErc20MetadataGet works without problems with this api config. Error looks liek following:
```
Response { type: "cors", url: "https://deep-index.moralis.io/api/account/balance?chain_name=kovan&address=0xEA8A39bfAB9E059Ec5f4F878862D0Ba52841725C", redirected: false, status: 500, ok: false, statusText: "Internal Server Error", headers: Headers, body: ReadableStream, bodyUsed: false }
```
Do you have any ideas, what am I doing wrong? 
Thank you for your help!:)

**Comment by ivan-liljeqvist** [comment]
Please post in https://forum.moralis.io - we have staff actively checking there
