### ISSUE TITLE
Select Pointer Interface Stuck

### ISSUE THREAD

**Issue by WoodsFiend** [MoralisWeb3/issue-tracker#86]
When editing an object by double clicking on its object id, if you try to select the Pointer from this screen the UI becomes stuck. Unable to select Save or Cancel and must refresh browser.

Server Version 0.0.235

Edit Object screen:
<img src="https://user-images.githubusercontent.com/35517586/127059742-9f979616-a27d-4c7d-94ba-63fa51137bbb.png" width="300" >

Stuck Here:
![image](https://user-images.githubusercontent.com/35517586/127059472-18cd0cdc-c753-4149-accf-3bd233ed1177.png)

**Comment by ivan-liljeqvist** [comment]
Please post in https://forum.moralis.io - we have staff actively checking there
