### ISSUE TITLE
Set up Cloud Functions in your IDE: Invalid script watch-cloud-file

### ISSUE THREAD

**Issue by ashbeech** [MoralisWeb3/issue-tracker#88]
Error: Invalid script watch-cloud-file
When I execute the watch-cloud-file and change to the correct path of your cloud file.
Current valid scripts: 
watch-cloud-folder
connect-local-devchain
update-server
create-server
add-contract
deploy
undeploy
get-logs
help

Should there be 'watch-cloud-file' or is this a UI typo?

**Comment by dani69654** [comment]
Hey @ashbeech 

The script `watch-cloud-file` has been renamed to `watch-cloud-folder`.
This new script listens to a folder instead of a single file.
You can find the related docs here: https://docs.moralis.io/moralis-admin-cli#watch-cloud-folder

Make sure to run the help command to find out all the parameters accepted by the script.

We are also considering to add the `watch-cloud-file` script back.
I will keep you posted if that happens.

**Comment by ashbeech** [comment]
Okay, altered code as follows, but unable to specify path to folder/file now:

moralis-admin-cli watch-cloud-folder --moralisApiKey xxx --moralisApiSecret xxx --moralisSubdomain xxx.usemoralis.com --moralisCloudFile ./cloud/CloudFile.js

Whatever I type, other than './' outputs:

`Error: Specify path to cloud functions folder`

**Comment by dani69654** [comment]
The script asks for a folder to listen, so you should not specify a js file.

In my example below, I have a folder in my Desktop called `a`.

What I run is:

`moralis-admin-cli watch-cloud-folder -p /Users/dani/Desktop/a`

The script will guide you step by step.

**Comment by ashbeech** [comment]
Thanks thus far, but still not working. I'm able to get as entering via terminal:

`moralis-admin-cli watch-cloud-folder -p /Users/xxx/dev/moralis/cloud --moralisApiKey xxx --moralisApiSecret xxx --moralisSubdomain xxx.usemoralis.com`

```
Select mode: 
(0)manual save
(1)auto save
1
```
…

Then nothing, just hangs/no further process unless I ctrl + C exit.

What should be happening once confirmed 'auto save' and how do I get the Moralis instance to use my local cloud file?

**Comment by dani69654** [comment]
The script is listening the JS file inside the folder: `/Users/xxx/dev/moralis/cloud`.
Create a new javascript file in that folder, write something and save it. It will be pushed to cloud automatically.

**Comment by ashbeech** [comment]
Yep, done that, so the cloud function folder listener is working, just no confirmation; how do I know it's worked… test cloud function written in the IDE via the JS Console?

Cheers.

**Comment by dani69654** [comment]
Whenever you save a .js file inside the folder specified, you will see
`Changes Uploaded Correctly` printed in the terminal.
![image](https://user-images.githubusercontent.com/60792849/128184056-e995ae7f-8744-4a85-96e2-21dec74c9566.png)

You will also see your code in your Moralis admin area -> cloud functions

**Comment by dani69654** [comment]
@ashbeech The `watch-cloud-file` script is now back in the moralis-admin-cli

**Comment by ashbeech** [comment]
`File Uploaded Correctly`

Cheers.
